In [1]:
from _lib import *
from data import *

- load all the historical data and universe

In [2]:
boa = load_star_board()
tickers = boa["ticker"].tolist()
qt.log.info(f"no of tickers on STAR board - [{len(tickers)}]")

[JUSTY.LOG]	2026-05-09 22:26:47,860 - qt.common.help - INFO - no of tickers on STAR board - [609]

- rebalance parameters

In [ ]:
eff_date = dt.date(2026, 3, 14)
annc_date = dt.date(2026, 2, 28)
cutoff_date = dt.date(2026, 1, 31)
hist_start = dt.date(2025, 2, 1)
cutoff_10 = (cutoff_date + pd.offsets.BDay(10)).date()
# sse_holidays = load_sse_holidays()

- get listing date

In [5]:
history = load_historical_data_ohlcv(tickers, hist_start, cutoff_date)

- add scraped data from sse

In [6]:
# merge info_df and tu on ticker
t_ld = get_listing_dates(tickers)

# add listing date to star board
boa = pd.merge(boa, t_ld, on="ticker", how="outer")

- special treatment securities

In [7]:
st_securities = boa[boa['st']]['ticker'].tolist()
qt.log.info(f"[{len(st_securities)}] ST securities: {st_securities}")

[JUSTY.LOG]	2026-05-09 22:27:03,129 - qt.common.help - INFO - [12] ST securities: ['688022', '688033', '688053', '688066', '688076', '688184', '688201', '688270', '688287', '688496', '688622', '688646']

- eligibility
	- Listing time > 6 months. 
		1. If no of securities listed > 12 months is b/w 100 to 150 then requirement changes to > 12 months
	- For securities with daily avg total market_cap since initial listing in top 5, listing time should be > 3 months as of 10th trading days after end date of data (cutoff date)
	- For securities with daily avg total market_cap since initial listing in top 3, listint time should be > 1 month
	- Non-* ST securities
	- No violation of laws/reg, no financial problems etc

In [8]:
history_after_cof = history.copy()

In [12]:
univ = boa[[
	'ticker', 'listing_date', 'name', 'market_cap', 'st', 'shares_total', 
	'shares_tradable'
	]].copy()
univ = univ[~univ['st']].reset_index(drop=True)

univ['month_to_cof'] = univ['listing_date'].apply(lambda d: get_months_from_cutoff(d, cutoff=cutoff_date))
univ['month_to_cof10'] = univ['listing_date'].apply(lambda d: get_months_from_cutoff(d, cutoff=cutoff_10))

# add shares outstanding from yfinance
t_yf = get_yf_info(tickers=univ['ticker'].tolist())
univ = pd.merge(
	univ, 
	t_yf[[
		'ticker', 'shs_os_yf', 
		# 'shs_ff_yf'
		]], 
	on='ticker', how='left')

# if shs_os_yf is not null, use it as shs_total, otherwise use shares_total
# univ.loc[univ['shs_os_yf'] != 0, 'shs_for_avg'] = univ['shs_os_yf']
# univ.loc[univ['shs_os_yf'] == 0, 'shs_for_avg'] = univ['shares_total']
univ['shs_for_avg'] = univ['shares_tradable']

# add avg total mcap and avg value traded
avg_val_traded_n_mcap = get_avg_vol_mcap(history, univ, tickers=univ['ticker'].unique().tolist(), shs_col='shs_for_avg')

univ = pd.merge(univ, avg_val_traded_n_mcap, on='ticker', how='left')
univ['tmcap_rank'] = univ['avg_total_mcap'].rank(ascending=False, method='min')
univ['vtrad_rank'] = univ['avg_val_traded'].rank(ascending=False, method='min')

In [13]:
if eff_date.month == 6:
	# read weight of existing index
	curr_s50 = load_star50_weights()

	# add weight column
	univ = pd.merge(univ, curr_s50[['ticker', 'curr_weight']], on='ticker', how='left')

elif eff_date.month == 3:
	qt.log.info(f"loading march rebal etf list")
	curr_s50 = load_star50_march_weights()
	univ['curr_weight'] = univ['ticker'].isin(curr_s50)

[JUSTY.LOG]	2026-05-09 22:27:34,905 - qt.common.help - INFO - loading march rebal etf list

- add eligibility

In [14]:
no_of_securities_mt_12m = len(univ[univ['month_to_cof'] >= 12])
listing_month_cutoff = 12 if no_of_securities_mt_12m > 100 else 6
qt.log.info(f"Listing month cutoff: {listing_month_cutoff} months (securities with month_to_cof >= {listing_month_cutoff}: {no_of_securities_mt_12m})")

univ['listing_elig'] = (
	((univ['tmcap_rank'] <= 3) & (univ['month_to_cof'] >= 1)) |
	((univ['tmcap_rank'] <= 5) & (univ['month_to_cof10'] >= 3)) |
	(univ['month_to_cof'] >= listing_month_cutoff)
)

univ = univ[univ['listing_elig']].reset_index(drop=True)
univ['vtrad_rank2'] = univ['avg_val_traded'].rank(ascending=False, method='min')

# drop 10% stocks based on avg value traded rank
univ = univ[univ['vtrad_rank2'] <= 0.9*len(univ)].reset_index(drop=True)
univ['tmcap_rank2'] = univ['avg_total_mcap'].rank(ascending=False, method='min')
univ = univ.sort_values('tmcap_rank2').reset_index(drop=True)

[JUSTY.LOG]	2026-05-09 22:27:35,576 - qt.common.help - INFO - Listing month cutoff: 12 months (securities with month_to_cof >= 12: 558)

In [15]:
# univ.set_index('ticker')[['shares_total', 'shares_tradable', 'shs_os_yf', 'shs_ff_yf']].plot()

In [17]:
qt.view(univ)

Grid(columns_fit='auto', compress_data=True, css_rules_down=['.number-cell {text-align: left;width: 10;}', '.l…

In [16]:
comp_incl = univ[
	(univ['tmcap_rank2'] <= 40) &
	(univ['curr_weight'].isna())
]
comp_excl = univ[
	(univ['tmcap_rank2'] > 60) &
	(~univ['curr_weight'].isna())
]
print(f"inclusion stocks : \n")
qt.view2(comp_incl)
print(f"exclusion stocks : \n")
qt.view2(comp_excl)

inclusion stocks :

exclusion stocks :

- reporting and stuff

In [ ]:
tmcap_40 = univ[univ['tmcap_rank2'] == 40]['avg_total_mcap'].values[0]
tmcap_60 = univ[univ['tmcap_rank2'] == 60]['avg_total_mcap'].values[0]
qt.log.info(f"TMCap of 40th stock: {tmcap_40:.3f} B CNY, TMCap of 60th stock: {tmcap_60:.3f} B CNY")

- march testing

In [ ]:
univ[univ['ticker'].isin(
	[
		'688498', '688110', '688002',
		'688114', '688278', '688349'	
  	]
)]

In [ ]:
excls = ['688220', '688301', '688385']
incls = ['688213', '688278', '688578']
res_list = ["688608", "688425", "688361", "688568", "688172",]
univ[univ['ticker'].isin(excls)]
univ[univ['ticker'].isin(incls)]
univ[univ['ticker'].isin(res_list)]