In [1]:
from help import *

- gather all the tickers

In [2]:
delisted_tickers = ["688086.SH", "688555.SH"]

In [5]:
star_board = pd.read_csv('../data/star_board.csv')
tickers = star_board['stock_code'].tolist()

In [6]:
qt.log.info(f"len(tickers)={len(tickers)}, len(delisted_tickers)={len(delisted_tickers)}")

[JUSTY.LOG]	2026-05-10 00:09:25,572 - qt.common.help - INFO - len(tickers)=609, len(delisted_tickers)=2

- free float market cap

In [21]:
ticker = tickers[0]

In [72]:
def load_ohlcv_one_ticker(ticker):
	try:
		tik = ticker.split(".")[0]
		t = pd.read_csv(f"../ohlcv/{ticker}")
		t['ticker'] = tik
		return t
	except Exception as e:
		qt.log.warning(f"error loading ohlcv data for {ticker}: {e}")
		return pd.DataFrame()

def load_historical_data_ohlcv(tickers, start_date=None, end_date=None):
	if isinstance(tickers, str):
		tickers = [tickers]

	history = pd.concat([load_ohlcv_one_ticker(f) for f in os.listdir("../ohlcv") if f.endswith(".csv")])
	history["date"] = pd.to_datetime(history["date"]).dt.date

	if start_date is not None:
		history = history[history["date"] >= start_date]

	if end_date is not None:
		history = history[history["date"] <= end_date]

	history = history.sort_values(["ticker", "date"]).reset_index(drop=True)
	return history

In [37]:
ticker = '688050'
tik = yf.Ticker(f"{ticker}.SS")
filename = f"../ohlcv/{ticker}.csv"

# load and format history
hist = tik.history(period="max", auto_adjust=False)

In [45]:
hist = hist.reset_index('Date')
hist['Date'] = hist['Date'].dt.date

In [46]:
qt.view(hist)

Grid(columns_fit='auto', compress_data=True, css_rules_down=['.number-cell {text-align: left;width: 10;}', '.l…

In [ ]:
t1 = load_ohlcv_one_ticker(f'{ticker}.csv')
t1['date'] = pd.to_datetime(t1['date']).dt.date
qt.view(t1)

Grid(columns_fit='auto', compress_data=True, css_rules_down=['.number-cell {text-align: left;width: 10;}', '.l…

In [49]:
t0 = load_historical_data_ohlcv(tickers)

In [90]:
t0[t0['dividends']!=0].sort_values('dividends')

,date,open,high,low,close,volume,dividends,stock_splits,ticker
102586,2025-07-17,18.00,18.00,16.94,17.32,6369749,0.00,1.20,688085
501010,2025-06-20,7.38,7.50,7.30,7.31,8827355,0.01,0.00,688549
309033,2024-09-13,6.25,6.25,5.92,5.94,1813147,0.01,0.00,688285
636860,2024-08-08,11.14,11.32,10.99,11.17,7522263,0.01,0.00,688728
473438,2023-08-17,4.57,4.66,4.48,4.64,5076569,0.01,0.00,688509
...,...,...,...,...,...,...,...,...,...
82018,2022-06-16,84.15,86.21,83.44,83.76,1909956,5.00,1.48,688068
89019,2023-06-29,44.59,44.91,41.53,42.35,1186073,5.00,1.40,688075
321992,2022-06-16,104.35,109.25,103.78,105.41,3018448,5.15,1.40,688298
426855,2022-05-30,84.03,84.03,77.17,77.49,3183595,6.76,0.00,688399
553020,2023-06-09,57.54,57.54,53.97,54.24,874214,6.76,1.48,688606

In [92]:
qt.view(t0[t0['ticker'] == '688606'])

Grid(columns_fit='auto', compress_data=True, css_rules_down=['.number-cell {text-align: left;width: 10;}', '.l…

In [51]:
qt.view(t0[t0['stock_splits']!=0].sort_values('stock_splits'))

Grid(columns_fit='auto', compress_data=True, css_rules_down=['.number-cell {text-align: left;width: 10;}', '.l…

In [89]:
ticker = yf.Ticker("688050.SS")
ticker.actions

                           Dividends  Stock Splits
Date
2021-05-26 00:00:00+08:00       0.16          0.00
2022-07-27 00:00:00+08:00       0.21          0.00
2023-05-23 00:00:00+08:00       0.28          0.00
2024-06-05 00:00:00+08:00       0.27          1.80
2025-07-18 00:00:00+08:00       0.35          0.00

In [59]:
t5 = ak.stock_zh_a_hist(symbol="688050", period="daily", start_date="20240101", end_date="20260509", adjust="qfq")

In [70]:
t5.columns = ['date', 'stock_code', 'open', 'close', 'high', 'low', 'volume', 'turnover', 'volatility', 'change1', 'change2', 'turnoer_rate']

In [71]:
qt.view(t5)

Grid(columns_fit='auto', compress_data=True, css_rules_down=['.number-cell {text-align: left;width: 10;}', '.l…

In [65]:
t1[t1['date'] >= dt.date(2024,1, 2)]

,date,open,high,low,close,volume,dividends,stock_splits,ticker
833,2024-01-02,170.55,170.55,164.43,167.01,793181,0.00,0.00,688050
834,2024-01-03,165.73,167.90,164.61,164.69,378938,0.00,0.00,688050
835,2024-01-04,165.46,165.46,160.86,162.47,379322,0.00,0.00,688050
836,2024-01-05,161.67,163.51,158.13,161.29,732219,0.00,0.00,688050
837,2024-01-08,160.67,161.13,153.82,157.59,965976,0.00,0.00,688050
...,...,...,...,...,...,...,...,...,...
1393,2026-04-29,50.90,51.34,50.69,50.90,1424244,0.00,0.00,688050
1394,2026-04-30,51.08,52.69,50.81,51.29,2108839,0.00,0.00,688050
1395,2026-05-06,51.76,51.76,51.00,51.11,2338968,0.00,0.00,688050
1396,2026-05-07,51.14,51.38,50.42,50.61,1983138,0.00,0.00,688050
1397,2026-05-08,NaN,NaN,NaN,NaN,1423495,0.00,0.00,688050